ingest:
  - source: 'web'
    source_path: 'https://www.unibas.ch/en/University/About-University.html'
    chunk_size: 2000
    chunk_overlap: 200
embedding:
    class_name: Nomic-v1.5
vector_store:
    connectionString: 'mongodb+srv://admin:setup@rag-hackathon-cluster.lsyah.mongodb.net'
    dbName: 'chatbot'
    collectionName: 'embedded_content'
    embeddingKey: 'embedding'
    textKey: 'text'
    numCandidates: 150
    minScore: 0.1 
    vectorSearchIndexName: 'vector_index'
    similarityFunction: 'cosine'
llms:
    class_name: Fireworks
    model_name: 'accounts/fireworks/models/mixtral-8x22b-instruct'
    temperature: ''
    top_p: ''
    top_k: ''
